# Generated by Django 6.0.6 on 2026-07-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='fotografia',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%M/%D/'),
        ),
    ]
